from PyQt5 import QtCore, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(994, 518)
        MainForm.setMinimumSize(QtCore.QSize(994, 300))
        self.mainLayout = QtWidgets.QVBoxLayout(MainForm)
        self.mainLayout.setContentsMargins(0, -1, 0, -1)
        self.mainLayout.setSpacing(7)
        self.mainLayout.setObjectName("mainLayout")
        self.layout = QtWidgets.QGridLayout()
        self.layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout.setContentsMargins(20, 0, 20, 0)
        self.layout.setHorizontalSpacing(20)
        self.layout.setVerticalSpacing(7)
        self.layout.setObjectName("layout")
        self.del_btn = QtWidgets.QPushButton(MainForm)
        self.del_btn.setObjectName("del_btn")
        self.layout.addWidget(self.del_btn, 1, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(MainForm)
        self.save_btn.setObjectName("save_btn")
        self.layout.addWidget(self.save_btn, 1, 2, 1, 1)
        self.new_btn = QtWidgets.QPushButton(MainForm)
        self.new_btn.setObjectName("new_btn")
        self.layout.addWidget(self.new_btn, 1, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.table = QtWidgets.QTableWidget(MainForm)
        self.table.setMinimumSize(QtCore.QSize(950, 200))
        self.table.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setObjectName("tableWidget")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(310)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.layout.addWidget(self.table, 0, 0, 1, 3)
        self.mainLayout.addLayout(self.layout)
        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Password Manager 2000"))
        self.del_btn.setText(_translate("MainForm", "Удалить"))
        self.save_btn.setText(_translate("MainForm", "Сохранить"))
        self.new_btn.setText(_translate("MainForm", "Создать пароль"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainForm", "Название"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainForm", "Логин"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainForm", "Пароль"))
